// Code generated by mockery v2.5.1. DO NOT EDIT.

package reloadmock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Reloader is an autogenerated mock type for the Reloader type
type Reloader struct {
	mock.Mock
}

// Reload provides a mock function with given fields: ctx, id
func (_m *Reloader) Reload(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
